defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: pseudocms_dev

test:
  <<: *defaults
  database: pseudocms_test
